# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10000)),
                ('user_id', models.IntegerField(max_length=3)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
    ]
