# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.IntegerField(max_length=3, null=1),
        ),
    ]
