# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_auto_20160801_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
